version: '3.8'

services:
  nodejs:
    build: .
    container_name: nodejs-container
    ports:
      - "3000:3000"  # Utilisation du port 3000 sur l'hôte pour accéder à Node.js
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - mynetwork  # Ajout du service nodejs au réseau commun
    depends_on:
      - mysql  # Garantir que MySQL démarre avant Node.js

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:   
      - "3306:3306"  # Utilisation du port 3306 sur l'hôte pour accéder à MySQL
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork  # Ajout du service mysql au réseau commun

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-container
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8083:80"  
    depends_on:
      - mysql  # Dépend de MySQL
    networks:
      - mynetwork  # Ajout du service phpmyadmin au réseau commun

  vscode:
    image: codercom/code-server:latest
    container_name: vscode-container
    environment:
      - PASSWORD=1234 # Définit un mot de passe pour accéder à VSCode
    ports:
      - "8080:8080"  # Accès à VSCode via le port 8080
    volumes:
      - ./app:/home/coder/project  # Montage du répertoire de ton projet
    command: code-server --auth password  # Active l'authentification avec mot de passe
    networks:
      - mynetwork  # Ajout du service vscode au réseau commun

volumes:
  mysql-data:

networks:
  mynetwork:  # Définition du réseau commun
    driver: bridge  # Utilisation du driver bridge
